### ISSUE TITLE
I can't get this to work

### ISSUE THREAD

**Issue by mocards1776** [aberonni/gmail-app-badge-notification#1]
Is this working? I cannot get it to work.

Thanks!

**Comment by aberonni** [comment]
It's working for me.

Can you give me some info on your setup? Did you already have Gmail as an app? What operating system are you on? What Chrome version?

**Comment by aberonni** [comment]
@mocards1776 actually it broke for me and I just released a new version with a fix. Let me know if that fixes it for you.

**Comment by mocards1776** [comment]
It worked! Thanks!

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/17/20,
10:46:32 AM

**Comment by mocards1776** [comment]
It does seem to always display a one (1) though...is that normal? Not a
huge deal...but just thought I would ask.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/17/20,
10:51:50 AM

**Comment by aberonni** [comment]
That's odd. I see the correct number of unread. What number do you have in the left hand column next to "Inbox"? That's where I get the number from.

**Comment by aberonni** [comment]
@mocards1776 I just published a new version that might fix your issue. Let me know.
