### ISSUE TITLE
inboxize gmail

### ISSUE THREAD

**Issue by PhantomXXXPA** [aberonni/gmail-app-badge-notification#11]
doctype html><html dir="ltr" lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Apps</title><script src="edge://resources/js/assert.js"></script><script src="edge://resources/js/promise_resolver.js"></script><script src="edge://resources/js/cr.js"></script><script src="edge://resources/js/cr/ui.js"></script><script src="edge://resources/js/cr/ui/keyboard_shortcut_list.js"></script><script src="edge://resources/js/cr/ui/command.js"></script><script src="edge://resources/js/parse_html_subset.js"></script><script src="edge://resources/js/load_time_data.js"></script><script src="edge://resources/js/util.js"></script><script src="/strings.js"></script><style>/* Copyright (C) Microsoft Corporation. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file. */

body {
  font-family: "system-ui", sans-serif;
  font-size: 14px;
  background-color: rgb(247, 247, 247);
  margin: 0;
}

@media (forced-colors:none) {
  input::selection {
    color: #FFF;
    background: #0078D4;
  }
}

@media (prefers-color-scheme: dark) {
  body {
    background-color: rgb(51, 51, 51);
  }
}
@media (forced-colors:none) and (prefers-color-scheme: dark) {
  input::selection {
    color: #000;
    /* RGBA because Blink applies an opacity otherwise */
    background: rgba(147, 184, 231, 0.996);
    opacity: 1;
  }
}</style><style>body {
      background: transparent !important;
    }

    #app-root {
      height: 100%;
      overflow: hidden;
      position: absolute;
      width: 100%;
    }

    #modal-root {
      position: fixed;
    }

    #drag-root {
      pointer-events: none;
      position: fixed;
      z-index: 999;
    }</style></head><body style="margin: 0;"><div id="app-root"></div><div id="drag-root"></div><div id="modal-root"></div><script defer="defer" src="/lib_react.chunk.js"></script><script defer="defer" src="/lib_common.chunk.js"></script><script defer="defer" src="/apps.bundle.js"></script></body></html>

**Comment by aberonni** [comment]
No idea what is going on here lol
