### ISSUE TITLE
Stopped working in latest Chrome versions

### ISSUE THREAD

**Issue by gapl** [aberonni/gmail-app-badge-notification#13]
Seems like this extension has stopped working on the latest Chrome versions. I absolutely loved it so far! I was able to verify this issue on multiple accounts.

* Chrome version: `Version 101.0.4951.54 (Official Build) (x86_64)`
* Extension version: `1.0.3`
* Extensions permissions: `*://*.mail.google.com/*`

**Comment by reskume** [comment]
Can second this. Doesn't work for me with the new Chrome. Versions identical to OP.

**Comment by oltodo** [comment]
Same issue for me. I've just removed and recreated the app and it worked again.

**Comment by gapl** [comment]
I can confirm this now works again. I've tried the same procedure previously, but it didn't work then.

Thanks for letting us know!
