### ISSUE TITLE
important and unread

### ISSUE THREAD

**Issue by rcmaross68** [aberonni/gmail-app-badge-notification#17]
I wonder if it would be hard to change this so you can optionally have the badge be the number of important and unread emails.  In this world of google searching inboxes I never actually move things out of my inbox anymore and I get so many emails that is it ridiculous but gmail does a pretty good job of knowing which are important to me so I use "priority inbox" and it works really well.  SO it would be ideal if the badge count supported priority inbox in that it would only show unread and important (ie high priority) message.

**Comment by aberonni** [comment]
Hey there, thanks for opening an issue for this.

I'm not actively developing the extension; I'm not using it anymore, nor do I have time to test it properly. But I'll leave the issue open in case you or someone else would like to contribute to the code base and add this feature - I'm sure others would like this feature, too.

**Comment by rcmaross68** [comment]
i think the change is trivial, except I am not sure how to make it
configurable, but I dont know how to create the extension and try it.  any
ptrs to how to do that would be greatly appreciated.

Thanks

Ryan

**Comment by aberonni** [comment]
The current implementation is dead simple. The change is somewhat trivial, but adding configuration options would already increase the complexity. It shouldn't be too complicated but it does require time.

If you're unsure how extension development in general works, I think this would be a great place to start: https://developer.chrome.com/docs/extensions/get-started

**Comment by papaharry** [comment]
First of all thank you for the really good extension @aberonni. I just started using it.

I had a look on the issue and I have a possible solution (tested locally and looks ok), so if this is something that @rcmaross68 is after, I can do a PR with my horrible solution (but hey, it works).

So essentially, when you click on the extension icon, a small pop-up appears at the bottom of the screen and you type the labels you want to filter on. If you leave it blank it will be the same as it is now and it will add the badge for all unread emails on inbox.

The pop-up is super basic and it looks like this.

![image](https://github.com/user-attachments/assets/705b8fc6-ce0c-4afa-9941-b4bbfbe7407c)

If that's what you're after, happy to do the PR. But as @aberonni already mentioned, this implementation increases complexity compared to the nice and simply current implementation.

edit: Once you click "Set Label" it disappears again

**Comment by aberonni** [comment]
@papaharry I'd be open to accepting a PR with this contribution, but I would rather change the UI to use an "options page" rather than a popup like you've implemented.

You can see an example of how that works in this other extension that I've built: https://github.com/aberonni/open-in-vscode

Converting your working code to fit that layout should not be too difficult, but lmk if you need help.

You could also decide to just host a fork of your own with your rudimentary implementation - maybe that is enough for other users and it's not worth the extra effort.

**Comment by papaharry** [comment]
Thank you @aberonni, thank you for the suggestion.

I ll have a look and will let you know if I need any help.

**Comment by papaharry** [comment]
Hello again,

Not sure if that's what is expected given that everything will stay online, but I implemented it with an options setting.
When you right click, you get the option to add the label 
![image](https://github.com/user-attachments/assets/2e9d4984-ed13-45d1-af44-59a922c00147)

or you can click on the extension and click "configure"
![image](https://github.com/user-attachments/assets/5403f674-d33a-4801-aebe-5e162ee45f86)


and when you click it, a new tab opens on the browser to add the label. The functionality about the labels stays the same, as in, if you leave it empty and "save" it, it will be back to the default/current behaviour.

The new tab is a basic looking tab like this (see example screenshot)
![image](https://github.com/user-attachments/assets/d455914b-ddba-49ef-b38f-8a0eae185780)

Edit: added your css and look much better:
![image](https://github.com/user-attachments/assets/2ce292c5-4c70-4e59-9236-0f0d823d1dfc)

**Comment by papaharry-ppro** [comment]
I copied your css too from the repo you shared and looks much better
![image](https://github.com/user-attachments/assets/518cea97-0896-41bc-b440-199899fa3e71)

**Comment by papaharry** [comment]
Hey @aberonni , wondering if you had time to check the proposal and/or the PR (first time I am writing javascript so if it's completely rubbish let me know).

No rush if you haven't. Just wondering if I should keep it separate to yours as a couple of colleagues asked me about it because they are interested and they want the filtering on too.

**Comment by aberonni** [comment]
@papaharry Hey, yes sorry I haven't gotten back to you yet. I hope to get a chance to have a better look at the PR on Saturday but for the most part it is looking good :v:

**Comment by papaharry** [comment]
No worries at all. Thank you again for making the time for that.

**Comment by esseti** [comment]
is there any news or the possibility to install the extension with this feature? It would be very handy and game changer.

**Comment by aberonni** [comment]
I just published the new version with the fix to the chrome web store. Keep an eye out for the new version (v1.2.0)

**Comment by esseti** [comment]
> I just published the new version with the fix to the chrome web store. Keep an eye out for the new version (v1.2.0)

i've `Gmail app badge notification 1.2.1` but still i see the counter is for "all unread" and not just priority unread. do i need to change some settings somewhere?

**Comment by papaharry** [comment]
Hey @esseti, right click on the app and you will see the option "Configure Gmail Badge".
![image](https://github.com/user-attachments/assets/82f3dd4b-0746-44c8-a3a3-2641e8c7737c)

Then you can type the label you want to see notifications for and then you can close that tab.

![image](https://github.com/user-attachments/assets/fe465fb2-7218-4ff9-a2c4-194b8018c3a8)

If you want to go back to track everything again, just remove the label and click save

**Comment by esseti** [comment]
great! 
i suggest to add this to the readme or to the front page

**Comment by Dino7405** [comment]
Hello, I had some questions about this label feature.  Which label types are supported?  I tried entering Inbox or Primary, and the badge disappears even though there is unread mail in my Inbox/Primary.  Are "categories" not supported? - categories such as Primary, Promotions, Updates, Forums, etc.  The only label I could get to work is "Important" which reduced the # count on the badge - which makes sense as it only counts emails marked as Important.  It would be nice if Inbox or Primary was supported.

**Comment by papaharry** [comment]
Hi @Dino7405, as you correctly mentioned, these are categories and although they are supported, they need to correctly reference the default key. The "Important" category has been mapped already [see here](https://github.com/aberonni/gmail-app-badge-notification/blob/master/src/options.js#L15-L16), but the rest of them haven't. The custom labels you can create don't need any kind of mapping.

**Comment by Dino7405** [comment]
I'm not a programmer, so how do we get those categories mapped?  I'm not
sure what the default keys are.  Sorry for my ignorance, I'm just unclear
on what has to be done. Thanks!

**Comment by papaharry** [comment]
I can map some more values @Dino7405, but those will be mainly for spam, draft, etc . 
We also need to update the way it gets the results from `fullcount` to be based on `entry`

This is a bit of weird behaviour as when it is relying on fullcount, although it returns entries based on forums, promotions, etc, the fullcount stays 0. It has the same behaviour on the browser too, so looks like a feed issue rather than code issue.

If @aberonni is happy with that, I can do another PR.

**Comment by Dino7405** [comment]
Another wishlist item - allow user to customize the badge color.  Not sure if that is possible - is it controlled by Chrome?  Current badge color is black with white number.  If taskbar is in dark mode, the badge blends in.  This is a nitpicky thing, but would be cool if user could control the badge color.  On Microsoft Edge, app badges for PWAs are not black - they are colored based on the system accent color.

**Comment by papaharry** [comment]
I have opened a new issue and a PR to fix the issue with promotions, updates etc separately to track it.

Regarding the issue with the badge colour, this seems to be an OS thing. I am just getting the typical red dots on both light and dark thing (on MacOS Sequoia 15.2)

I would suggest to open a separate issue with that request in case someone else that comes here know how to fix it as this issue is closed and won't appear by default on the list of current issues

**Comment by Dino7405** [comment]
Thanks!  I'm not sure if I mentioned it in my previous email, but I'm on
Windows 11 with the latest version of Chrome - badges for Chrome PWAs/apps
on Windows 11 are always black background with white numbers.  However,
when using Microsoft Edge on Windows 11, badges for PWAs always take on the
color of the system accent color, so I think this is more tied to the
browser vs. the OS.

**Comment by papaharry** [comment]
I see. Unfortunately I can't test it as I am only running MacOS. I checked the [microsoft website](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) but the download of evaluation images has been disabled as of  October 23, 2024, so can't even test on a local VM.

I would suggest to open a new issue and maybe someone can help with that feature. macOS api doesn't allow that . It's always set to red circle and white writing or badge (at least for now)
