### ISSUE TITLE
Extension stopped working after installing Chrome Canary on same computer

### ISSUE THREAD

**Issue by danielastudilloaccedo** [aberonni/gmail-app-badge-notification#19]
Hi.
Since I have two different gmail accounts I installed Chrome and Chrome Canary to have two instances of the extension running. The extension worked ok on Chrome, but when I installed Canary and enabled the extension, the one in the original Chrome stopped working, and only worked on Canary. Now I uninstalled Canary, but the extension on Chrome does not work anymore, even if I reinstall everything from scratch.
Is there any lingering file that the extension creates that I should delete manually?

**Comment by aberonni** [comment]
Hey,

> Is there any lingering file that the extension creates that I should delete manually?

Not really. I also haven't used the extension in a long time so I'm not sure how/whether it's still working.

I assume you've already tried the [troubleshooting steps](https://github.com/aberonni/gmail-app-badge-notification/tree/master?tab=readme-ov-file#troubleshooting). Not sure what else to suggest I'm afraid.

**Comment by danielastudilloaccedo** [comment]
Yeah. I went through the troubleshooting.
The extension works for the basic use case. If you have just one account and just one Chrome browser, it works perfectly.
It is for the edge cases like me that behaves weirdly.
Being a developer myself I can understand if you are not maintaining this extension anymore. Thanks for putting it out there anyways ;)
