### ISSUE TITLE
Seems like this code broke something

### ISSUE THREAD

**Issue by findmory** [aberonni/gmail-app-badge-notification#21]
![Screenshot 2024-12-17 at 11 57 35 AM](https://github.com/user-attachments/assets/1ebca224-bbd1-410e-af4a-230f86951c47)

**Comment by aberonni** [comment]
Very sorry about that. I've pushed a new version (v1.2.1) to the web store, hopefully it will be published soon.

**Comment by aberonni** [comment]
v1.2.1 is available in the web store and should be working like before. Sorry for the inconvenience, and please let me know if there are still issues.
