### ISSUE TITLE
Gmail app badge notification not working

### ISSUE THREAD

**Issue by noxvoortella** [aberonni/gmail-app-badge-notification#25]
I have used the Chrome Gmail app badge notification extension for years, but it suddenly does not show the badge count. I've uninstalled, reinstalled, and inferred with your troubleshooting info here on GitHub... nothing seems to resolve this issue. I hope you can provide more guidance. Thank you!

**Comment by noxvoortella** [comment]
As soon as I submitted this issue, it somehow resolved itself. What a time to be alive 🤣

**Comment by aberonni** [comment]
What a rollercoaster 😂
