### ISSUE TITLE
No working on Mac Big Sur

### ISSUE THREAD

**Issue by ibread** [aberonni/gmail-app-badge-notification#4]
Thx for building the extension, I think it's exactly what I want: showing unread count for Gmail in a separated window. 

However, it doesn't seem to work for me:

1) there is no badge count
2) when check the extension status, it shows the following:

<img width="295" alt="Screen Shot 2020-12-12 at 9 48 17 PM" src="https://user-images.githubusercontent.com/633094/101985606-19db6f80-3cc4-11eb-9de9-4e4911da2f70.png">

What i've tried and not work:

1) uninstall Gmail app, and install it again
2) Quit Chrome and restart it
3) Disable other Gmail related extension (like Gmail checker), and restart Chrome.

Plz let me know if there is any more information needed. 

Thanks!

**Comment by rohit1600** [comment]
+1. Doesn't seem to work on Macbook w/ MacOS Monterey.

**Comment by aberonni** [comment]
AFAIK apps are not a thing anymore on mac, so closing this
