### ISSUE TITLE
Google Chat is showing Gmail badge

### ISSUE THREAD

**Issue by msmit423** [aberonni/gmail-app-badge-notification#9]
I also have a shortcut app for Google Chat and it's showing the same badge as Gmail. Reading/unreading emails updates the Google Chat badge the same as the Gmail. 

I want to add on too that this wasn't an issue prior to performing a Mac update and it also looked like a Google Chat update occurred. 

![image](https://user-images.githubusercontent.com/85519933/121080420-6605f900-c7a9-11eb-90c3-5adb5e9e9949.png)

Chrome: Version 91.0.4472.77 (Official Build) (x86_64)
Mac OS C̶a̶t̶a̶l̶i̶n̶a̶:̶ ̶1̶0̶.̶1̶5̶.̶7̶ ̶(̶1̶9̶H̶1̶2̶1̶7̶)̶ Updated to Big Sur and still an issue -- Big Sur v11.4

-Mike

**Comment by msmit423** [comment]
@aberonni -- Any idea on this one? Have you or anyone else experienced this?

**Comment by msmit423** [comment]
I also noticed that the Google Chat URL is now: https://mail.google.com/chat/u/0/#chat/welcome which I think is different than previously (but I can't confirm). Appears they're more closely integrating it into Gmail. 

The Gmail URL is https://mail.google.com/mail/u/0/#inbox. 

Perhaps there's something in the code that would be a quick update to filter out the /chat/ URL from displaying the badge? Sorry, I'm not a developer and don't know the first thing to look at but can help with research and testing 🙂

Would a possible fix be updating the manifest.json from "*://*.mail.google.com/*" to "*://*.mail.google.com/**mail/***"

**Comment by JavascriptPerformance** [comment]
Hello, would it be possible to re add this functionality, maybe as an optional? I have Chat inside Gmail and would like to use it without having an extra Chat window open, but since I don't get the badge for chat it is a bit inconvenient.

Thank you very much :)

**Comment by aberonni** [comment]
See comment in https://github.com/aberonni/gmail-app-badge-notification/issues/30
